# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 269d62edeae2b253d8ee48b42031de0631901992292609c74d7fbafd92ebd96ff1b9bf1827c000476b59be02121ee0b2250bb72b3e26549b4ad24a5c3807542c

test:
  secret_key_base: 29d04724a46de6d5145e31d84390ee184428033be67d329a274dab8423ac0e34a5847d47b5c754c7a1bdbb7872f32ca18c27ba0b6846af52b3d2ff6ee388fdd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
